controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - joint_base_1
#     interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

forward_position_controller:
  ros__parameters:
    joints:
      - joint_base_1
      - joint_1_2
      - joint_2_3
      - joint_3_4
      - joint_4_gripper
      - joint_gripper_vacuum
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
